"""NIM explanation schemas: inputs and outputs for the explanation service.

The explanation service wraps a deterministic assessment result in plain
language. Its output is additive only — it must never contradict the engine.

Contradiction guard (enforced in explanation_service.py):
The service must reject any explanation text that contradicts these five
engine output fields:
  - eligible
  - pathway_used
  - rule_status
  - tariff_outcome (status field)
  - confidence_class

If the explanation service fails or produces an invalid payload, the fallback
path produces a minimal deterministic summary from the engine fields with
`fallback_used=True`. The deterministic result is never blocked by explanation
failure.

Structured output:
  - text:        NIM-generated or fallback plain-language summary of the outcome.
  - next_steps:  Actionable guidance derived deterministically from engine
                 outputs (missing evidence, missing facts, readiness gaps).
                 Never generated by NIM to prevent hallucination.
  - warnings:    Notes about provisional rule status, incomplete confidence,
                 or non-in-force tariff schedules. Deterministic from engine
                 fields.
  - fallback_used: True when the deterministic summary was used instead of
                 the NIM-generated text.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.assessments import EligibilityAssessmentResponse


class ExplanationContext(BaseModel):
    """Input to the explanation service: the completed deterministic assessment.

    The service uses these fields to:
    1. Build the system prompt (what the engine decided and why).
    2. Validate the NIM model's explanation text against the decision fields.
    3. Produce next-step guidance grounded in real engine outputs.

    The explanation service must not alter or re-derive any field in `assessment`.
    """

    assessment: EligibilityAssessmentResponse
    persona_mode: str | None = None

    model_config = ConfigDict(extra="forbid")


class ExplanationResult(BaseModel):
    """Structured output of the explanation service.

    `text` is the plain-language explanation. It is None when:
    - The NIM model call failed or timed out.
    - The model output failed the contradiction guard.
    - NIM is disabled and the minimal fallback produces no text.

    `next_steps` lists actionable guidance derived deterministically from
    the engine fields (missing evidence, missing facts). NIM never writes
    this list.

    `warnings` lists operational notes derived deterministically from engine
    fields (provisional status, incomplete confidence, non-in-force tariff).
    NIM never writes this list.

    `fallback_used` is True when the deterministic summary was substituted
    for a NIM-generated explanation.
    """

    text: str | None = None
    next_steps: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    fallback_used: bool = False

    model_config = ConfigDict(extra="forbid")
