"""NIM explanation service: wrap a deterministic assessment in plain-language text.

Responsibility boundary:
- Owns the system-prompt construction that grounds NIM in the engine's output.
- Owns the contradiction guard: rejects any model text that contradicts the
  five protected deterministic decision fields (eligible, pathway_used,
  rule_status, tariff_outcome, confidence_class).
- Computes next_steps and warnings deterministically from engine fields —
  these are never generated by NIM.
- Returns a minimal deterministic fallback when the model fails or produces
  an invalid explanation.
- Does NOT alter any field in EligibilityAssessmentResponse.
- Does NOT access the database.
- Does NOT call the deterministic engine.

Contradiction guard:
  If eligible is True, explanation must not contain ineligibility language.
  If eligible is False, explanation must not contain eligibility language.
  If confidence_class is "incomplete", explanation must not claim a final
    determination.
  If rule_status is not "agreed", explanation must not call the rule agreed
    or binding.
  If tariff_outcome.status is not "in_force", explanation must not claim
    the rate is in force.

Fallback:
  On any failure (model error, guard rejection, invalid JSON), returns
  ExplanationResult with fallback_used=True and a minimal deterministic text
  that echoes the engine's key fields without interpretation.
"""

from __future__ import annotations

import json
import logging

from app.schemas.assessments import EligibilityAssessmentResponse
from app.schemas.nim.explanation import ExplanationResult
from app.services.nim.client import NimClient, NimClientError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Contradiction guard phrase sets
# ---------------------------------------------------------------------------

# Phrases that assert the goods ARE eligible — reject these when eligible=False
_ELIGIBLE_CLAIM_PHRASES: frozenset[str] = frozenset({
    "is eligible",
    "are eligible",
    "will be eligible",
    "qualifies for preferential",
    "meets the rules of origin",
    "satisfies the rules of origin",
    "will qualify",
    "does qualify",
    "confirmed eligible",
})

# Phrases that assert the goods are NOT eligible — reject these when eligible=True
_INELIGIBLE_CLAIM_PHRASES: frozenset[str] = frozenset({
    "not eligible",
    "ineligible",
    "does not qualify",
    "will not qualify",
    "cannot qualify",
    "fails to qualify",
    "does not meet the rules of origin",
    "confirmed ineligible",
})

# Phrases that claim a complete/final determination — reject for incomplete assessments
_FINAL_DETERMINATION_PHRASES: frozenset[str] = frozenset({
    "final determination",
    "complete assessment",
    "definitive result",
    "definitive assessment",
    "fully compliant",
})

# Phrases that claim the rule is agreed/binding — reject when rule_status != "agreed"
_AGREED_RULE_PHRASES: frozenset[str] = frozenset({
    "agreed rule",
    "binding rule",
    "final rule",
    "rule is agreed",
    "rule has been agreed",
})

# Phrases that claim the tariff rate is in force — reject when tariff_outcome.status != "in_force"
_IN_FORCE_PHRASES: frozenset[str] = frozenset({
    "rate is in force",
    "tariff is in force",
    "rate in force",
    "currently in force",
    "in-force rate",
})

# ---------------------------------------------------------------------------
# NIM system prompt template
# ---------------------------------------------------------------------------

_NIM_EXPLANATION_SYSTEM_PROMPT_TEMPLATE = """\
You are a trade compliance assistant explaining an AfCFTA eligibility \
assessment result to {audience}.

Write a plain-language summary of the assessment outcome.

Rules:
- Base your explanation ONLY on the assessment data provided below.
- Do NOT contradict, reinterpret, or alter any assessment field.
- Do NOT invent rules, pathways, or facts not present in the data.
- Do NOT make predictions about future assessments.
- Do NOT promise or imply outcomes beyond what the data states.
- Keep the explanation factual, concise, and under 150 words.

Return ONLY a JSON object: {{"text": "<your plain-language explanation>"}}

Assessment data:
{assessment_json}
"""

# ---------------------------------------------------------------------------
# Audience label by persona mode
# ---------------------------------------------------------------------------

_AUDIENCE_BY_PERSONA: dict[str, str] = {
    "exporter": "an exporter",
    "officer": "a customs officer",
    "analyst": "a trade analyst",
    "system": "an automated system",
}
_DEFAULT_AUDIENCE = "a trade professional"

# ---------------------------------------------------------------------------
# Deterministic helpers
# ---------------------------------------------------------------------------


def _build_fallback_text(assessment: EligibilityAssessmentResponse) -> str:
    """Build a minimal factual summary directly from engine fields."""
    outcome = "eligible" if assessment.eligible else "not eligible"
    parts = [f"Assessment outcome: {outcome}."]
    if assessment.pathway_used:
        parts.append(f"Pathway used: {assessment.pathway_used}.")
    parts.append(f"Rule status: {assessment.rule_status.value}.")
    parts.append(f"Confidence: {assessment.confidence_class}.")
    if assessment.failures:
        parts.append(f"Failures: {'; '.join(assessment.failures)}.")
    if assessment.missing_facts:
        parts.append(f"Missing facts: {', '.join(assessment.missing_facts)}.")
    return " ".join(parts)


def _build_next_steps(assessment: EligibilityAssessmentResponse) -> list[str]:
    """Derive actionable next steps deterministically from engine outputs."""
    steps: list[str] = []
    for doc in assessment.missing_evidence:
        steps.append(f"Obtain and submit document: {doc.replace('_', ' ')}.")
    for fact in assessment.missing_facts:
        steps.append(f"Provide production fact: {fact.replace('_', ' ')}.")
    if assessment.eligible and assessment.evidence_required and not assessment.missing_evidence:
        steps.append(
            "Prepare the required evidence package before shipment: "
            + ", ".join(assessment.evidence_required) + "."
        )
    if not assessment.eligible and not assessment.missing_facts and not assessment.missing_evidence:
        steps.append(
            "Review the failed rule criteria to determine whether an alternative "
            "originating pathway is available."
        )
    return steps


def _build_warnings(assessment: EligibilityAssessmentResponse) -> list[str]:
    """Derive operational warnings deterministically from engine fields."""
    warnings: list[str] = []
    if assessment.confidence_class == "provisional":
        warnings.append(
            f"Rule status is '{assessment.rule_status.value}'. "
            "This assessment is provisional and subject to change when the rule is finalised."
        )
    if assessment.confidence_class == "incomplete":
        warnings.append(
            "Assessment is incomplete due to missing production facts. "
            "Results may change once all required facts are provided."
        )
    if (
        assessment.tariff_outcome is not None
        and assessment.tariff_outcome.status != "in_force"
    ):
        warnings.append(
            f"Tariff schedule status is '{assessment.tariff_outcome.status}'. "
            "Verify current rates before proceeding."
        )
    return warnings


def _build_assessment_summary_json(
    assessment: EligibilityAssessmentResponse,
) -> str:
    """Build a JSON-serialisable summary of the engine-protected fields for the prompt."""
    summary: dict[str, object] = {
        "eligible": assessment.eligible,
        "pathway_used": assessment.pathway_used,
        "rule_status": assessment.rule_status.value,
        "confidence_class": assessment.confidence_class,
        "failures": assessment.failures,
        "missing_facts": assessment.missing_facts,
        "missing_evidence": assessment.missing_evidence,
    }
    if assessment.tariff_outcome is not None:
        summary["tariff_outcome"] = {
            "status": assessment.tariff_outcome.status,
            "preferential_rate": (
                str(assessment.tariff_outcome.preferential_rate)
                if assessment.tariff_outcome.preferential_rate is not None
                else None
            ),
        }
    return json.dumps(summary, indent=2)


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------


class ExplanationService:
    """Generate a plain-language explanation for a deterministic assessment result.

    Injected with a NimClient for text generation. The contradiction guard
    is deterministic and must run before any model output is returned.

    next_steps and warnings are always computed deterministically from the
    engine fields — NIM never writes them.
    """

    def __init__(self, nim_client: NimClient) -> None:
        self.nim_client = nim_client

    async def generate_explanation(
        self,
        assessment: EligibilityAssessmentResponse,
        persona_mode: str | None = None,
    ) -> ExplanationResult:
        """Generate a plain-language explanation grounded in the assessment result.

        Builds a system prompt containing the deterministic decision fields,
        calls NIM for a plain-language text, and validates the output against
        the contradiction guard.

        next_steps and warnings are computed deterministically from the engine
        fields before the NIM call and are present in the result regardless of
        whether NIM succeeds.

        Falls back to a minimal deterministic text when:
        - the model call fails or times out
        - NIM is disabled (returns None)
        - the model output cannot be parsed as JSON
        - the model's explanation contradicts a protected field

        Raises nothing — deterministic fallback is always available.
        """
        # Deterministic fields — always computed, never from NIM
        next_steps = _build_next_steps(assessment)
        warnings = _build_warnings(assessment)

        # NIM explanation attempt with full fallback chain
        text, fallback_used = await self._generate_text(assessment, persona_mode)

        return ExplanationResult(
            text=text,
            next_steps=next_steps,
            warnings=warnings,
            fallback_used=fallback_used,
        )

    async def _generate_text(
        self,
        assessment: EligibilityAssessmentResponse,
        persona_mode: str | None,
    ) -> tuple[str, bool]:
        """Return (text, fallback_used) — always a non-None string."""
        audience = _AUDIENCE_BY_PERSONA.get(persona_mode or "", _DEFAULT_AUDIENCE)
        assessment_json = _build_assessment_summary_json(assessment)
        system_prompt = _NIM_EXPLANATION_SYSTEM_PROMPT_TEMPLATE.format(
            audience=audience,
            assessment_json=assessment_json,
        )

        try:
            raw = await self.nim_client.generate_json(system_prompt, "Explain this assessment.")
        except NimClientError as exc:
            logger.warning("NIM explanation call failed: %s", exc)
            return _build_fallback_text(assessment), True

        if raw is None:
            return _build_fallback_text(assessment), True

        try:
            data = json.loads(raw)
            text = str(data.get("text", "")).strip()
        except (json.JSONDecodeError, TypeError, AttributeError) as exc:
            logger.warning("NIM explanation parse error: %s", exc)
            return _build_fallback_text(assessment), True

        if not text:
            return _build_fallback_text(assessment), True

        if not self._passes_contradiction_guard(text, assessment):
            logger.warning(
                "NIM explanation failed contradiction guard, using fallback. "
                "eligible=%s confidence_class=%s",
                assessment.eligible,
                assessment.confidence_class,
            )
            return _build_fallback_text(assessment), True

        return text, False

    def _passes_contradiction_guard(
        self,
        explanation_text: str,
        assessment: EligibilityAssessmentResponse,
    ) -> bool:
        """Return True when explanation_text does not contradict the assessment.

        Checks the five protected fields:
        - eligible: text must not assert the opposite eligibility direction.
        - confidence_class: "incomplete" must not be called a final determination.
        - rule_status: non-agreed status must not be called agreed or binding.
        - tariff_outcome.status: non-in-force must not be called in force.
        - pathway_used: validated via eligible direction (pathway names not
          cross-checked directly to avoid brittle string matching).
        """
        lower = explanation_text.lower()

        # 1. eligible direction
        if assessment.eligible:
            if any(phrase in lower for phrase in _INELIGIBLE_CLAIM_PHRASES):
                return False
        else:
            if any(phrase in lower for phrase in _ELIGIBLE_CLAIM_PHRASES):
                return False

        # 2. confidence_class — incomplete assessment must not be called final
        if assessment.confidence_class == "incomplete":
            if any(phrase in lower for phrase in _FINAL_DETERMINATION_PHRASES):
                return False

        # 3. rule_status — non-agreed must not be called agreed or binding
        if assessment.rule_status.value != "agreed":
            if any(phrase in lower for phrase in _AGREED_RULE_PHRASES):
                return False

        # 4. tariff_outcome.status — non-in-force must not be called in force
        if (
            assessment.tariff_outcome is not None
            and assessment.tariff_outcome.status != "in_force"
            and any(phrase in lower for phrase in _IN_FORCE_PHRASES)
        ):
            return False

        return True
